"""flat_table

Revision ID: ba03965118e5
Revises: 620b597ee728
Create Date: 2024-05-23 19:11:33.929312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba03965118e5'
down_revision = '620b597ee728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_type', sa.String(length=32), nullable=False),
    sa.Column('price', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('square', sa.String(length=64), nullable=False),
    sa.Column('num_of_rooms', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=512), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flat_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flat_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_flat_square'), ['square'], unique=False)
        batch_op.create_index(batch_op.f('ix_flat_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flat_timestamp'))
        batch_op.drop_index(batch_op.f('ix_flat_square'))
        batch_op.drop_index(batch_op.f('ix_flat_price'))
        batch_op.drop_index(batch_op.f('ix_flat_company_id'))

    op.drop_table('flat')
    # ### end Alembic commands ###
