"""flat_table_v.0.1

Revision ID: d073fd367d84
Revises: ba03965118e5
Create Date: 2024-05-23 19:24:56.085982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd073fd367d84'
down_revision = 'ba03965118e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
