"""flat_table_v.0.2

Revision ID: fecd98aad7bd
Revises: d073fd367d84
Create Date: 2024-05-23 19:31:33.814651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecd98aad7bd'
down_revision = 'd073fd367d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flat', schema=None) as batch_op:
        batch_op.alter_column('square',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('num_of_rooms',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flat', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('num_of_rooms',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('square',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
